apiVersion: apps/v1
kind: Deployment

metadata:
  name: challenge-celery-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: challenge-celery-worker

  template:
    metadata:
      labels:
        app: challenge-celery-worker

    spec:
      containers:
        - name: celery-worker
          image: omarsa999/challenge-backend:latest
          imagePullPolicy: Always

          command:
            - uv
            - run
            - celery
            - -A
            - src.celery.celery:celery_app
            - worker
            - --loglevel=info
            - --pool=solo

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: SECRET_KEY

            - name: ALLOW_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: ALLOW_ORIGINS

            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: API_PREFIX

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: GOOGLE_API_KEY

            - name: IMAGEKIT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: IMAGEKIT_PRIVATE_KEY

            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: RABBITMQ_PASS

            - name: BROKER_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672//"

            - name: MAILTRAP_HOST
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: MAILTRAP_HOST

            - name: MAILTRAP_PORT
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: MAILTRAP_PORT

            - name: MAILTRAP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: MAILTRAP_USERNAME

            - name: MAILTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: MAILTRAP_PASSWORD

            - name: MAILTRAP_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: MAILTRAP_FROM_EMAIL

            - name: MAILTRAP_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: MAILTRAP_FROM_NAME

            - name: MAILTRAP_TO_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: MAILTRAP_TO_EMAIL

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: challenge-app-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: challenge-app-secret
                  key: POSTGRES_PASS

            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASS)@postgres:5432/$(POSTGRES_DB)"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"